config/routes.rb
Crawler::Rails::Engine.routes.draw do
  root 'sites#index'
  resources :batch_jobs, only: %i(index create update destroy) do
    post :queue_crawl_to_all_sites, on: :collection
  end

  resources :sites do
    post :crawl, on: :member
    post :queue_crawl, on: :member
    scope module: :sites do
      resources :page_sources, only: %i(new create edit update)
      resources :entries, only: %i(new create edit update) do
        post :test_run, on: :collection
      end
    end
  end

  resources :crawling_jobs, only: %i(index show)
end

app/models/crawler/rails/entry.rb
require 'open-uri'
require 'kconv'

module Crawler::Rails
  class Entry < ApplicationRecord

    SCRAPING_TIMEOUT = 10

    belongs_to :page_source

    has_many :crawling_logs

    def scrape_with_logging(crawling_job_id: )
      return unless enable
      crawling_log = crawling_logs.create!(crawling_job_id: crawling_job_id)
      result = scrape
      case result[:status]
      when :success
        crawling_log.status_success!
        crawling_log.update!(out: result[:message])
      when :error
        crawling_log.status_error!
        crawling_log.update!(error_trace: result[:message])
      else
        raise('unknown status')
      end
    rescue StandardError, SyntaxError => e
      crawling_log.status_error!
      crawling_log.update!(error_trace: e.inspect)
    ensure
      return crawling_log
    end

    def scrape
      Timeout.timeout(SCRAPING_TIMEOUT) do
        file = open(page_source.url)
        block = eval(scraping_code) # danger!!
        out = block.call(Nokogiri::HTML(file.read.toutf8, nil, 'utf-8'))
        Rails.logger.info out
        { status: :success, message: out }
      end
    rescue Timeout::Error
      { status: :error, message: "タイムアウト(#{SCRAPING_TIMEOUT}秒)になりました.処理は中断されました。" }
    rescue => e
      { status: :error, message: e.inspect }
    end
  end
end

app/models/crawler/rails/site.rb
module Crawler::Rails
  class Site < ApplicationRecord
    has_many :page_sources
    has_many :entries
    has_many :crawling_jobs

    scope :has_schedule, ->{
      where.not(schedule: [nil, ''])
    }

    def crawl
      crawling_job = crawling_jobs.create!
      crawling_logs =
        entries.map do |e|
          crawling_log = e.scrape_with_logging(crawling_job_id: crawling_job.id)
        end
      unless crawling_logs.all?(&:status_success?)
        crawling_job.update!(success: false)
      end
    end

    # TODO 重複してqueue しないようにする
    def crawl_to_tomorrow
      next_on = Date.today + 1.day
      run_at = "#{next_on} #{hh_mm_on_schedule}:00"
      delay(run_at: run_at).crawl
    end

    def schedule=(value)
      value == 'none' ? super(nil) : super
    end

    def hh_mm_on_schedule
      schedule
    end
  end
end

app/controllers/crawler/rails/sites/entries_controller.rb
module Crawler
  module Rails
    module Sites
      class EntriesController < ApplicationController
        def new
          @site = Site.find(params[:site_id])
          @entry = @site.entries.build
        end

        def create
          @site = Site.find(params[:site_id])
          @entry = @site.entries.build(entry_params)
          if @entry.save
            redirect_to @site, notice: '作成しました'
          else
            render :new
          end
        end

        def edit
          @site = Site.find(params[:site_id])
          @entry = @site.entries.find(params[:id])
        end

        def update
          @site = Site.find(params[:site_id])
          @entry = @site.entries.find(params[:id])
          if @entry.update(entry_params)
            redirect_to @site, notice: '作成しました'
          else
            render :edit
          end
        end

        def test_run
          @site = Site.find(params[:site_id])
          page_source = @site.page_sources.find(params[:page_source_id])
          entry = @site.entries.build(page_source_id: page_source.id,
                                      scraping_code: params[:scraping_code])
          @out = entry.scrape[:message]
          @out = [@out, Time.now.to_s].join("\n") # add timestamp
          respond_to do |format|
            format.js { render :test_run }
            format.any { head :not_found }
          end
        end

        private

        def entry_params
          params.required(:entry).permit!
        end
      end
    end
  end
end

app/controllers/crawler/rails/sites/page_sources_controller.rb
module Crawler
  module Rails
    module Sites
      class PageSourcesController < ApplicationController
        def index
          @page_sources = PageSource.all
        end

        def show
          @page_source = PageSource.find(params[:id])
        end

        def new
          @site = Site.find(params[:site_id])
          @page_source = @site.page_sources.build
        end

        def create
          @site = Site.find(params[:site_id])
          @page_source = @site.page_sources.build(page_source_params)
          if @page_source.save
            redirect_to @site, notice: '作成しました'
          else
            render :new
          end
        end

        def edit
          @site = Site.find(params[:site_id])
          @page_source = @site.page_sources.find(params[:id])
        end

        def update
          @site = Site.find(params[:site_id])
          @page_source = @site.page_sources.find(params[:id])
          if @page_source.update(page_source_params)
            redirect_to @site, notice: '作成しました'
          else
            render :edit
          end
        end

        private

        def page_source_params
          params.required(:page_source).permit!
        end
      end
    end
  end
end

app/controllers/crawler/rails/sites_controller.rb
module Crawler
  module Rails
    class SitesController < ApplicationController
      def index
        @sites = Site.all
      end

      def show
        @site = Site.find(params[:id])
      end

      def new
        @site = Site.new
      end

      def create
        @site = Site.new(site_params)
        if @site.save
          redirect_to @site, notice: '作成しました'
        else
          render :new
        end
      end

      def edit
        @site = Site.find(params[:id])
      end

      def update
        @site = Site.find(params[:id])
        if @site.update(site_params)
          redirect_to @site, notice: '作成しました'
        else
          render :edit
        end
      end

      def crawl
        @site = Site.find(params[:id])
        @site.delay.crawl
        redirect_to @site, notice: 'キューしました'
      end

      private

      def site_params
        params.required(:site).permit!
      end
    end
  end
end

app/views/crawler/rails/sites/entries/_form.html.slim
= form_for [@site, @entry] do |f|
  p
    = f.label :name
    = f.text_field :name
  p
    = f.label :enable
    = f.check_box :enable
  p
    = f.label :page_source
    = f.select :page_source_id, @site.page_sources.map { |x| [x.url, x.id] }
  p
    = f.label :scraping_code
    = f.text_area :scraping_code, size: '100x10'
  p
    = link_to 'test run', '#', data: 'test-run'

  h3 test run 結果
  pre data='result-for-test-run'
    | (test run の結果がここに表示されます)

  hr
  p scraping_code は、Block を記述してください。
  pre
    | #内部
    br
    | file = open(page_source.url)
    br
    | block = eval(scraping_code)
    br
    | block.call(Nokogiri::HTML(file.read.toutf8, nil, 'utf-8'))
    br
    br
    | #scraping_code のサンプルコード
    br
    | ->(doc) { doc.search('body').first.text }
    br

  p = f.submit

javascript:
  $(function() {
    $(document).on('click', '[data=test-run]', function(e) {
      var entry_page_source_id = $('#entry_page_source_id').val();
      var entry_scraping_code = $('#entry_scraping_code').val();
      $.post('#{test_run_site_entries_path(@site)}', { 'page_source_id': entry_page_source_id,
                                                       'scraping_code': entry_scraping_code, }
      ).fail(function(xhr, status, error) {
        $("[data=result-for-test-run]").html('サーバでエラーが起きました:' + xhr.responseText);
      });
      return false;
    })
  })

app/views/crawler/rails/sites/entries/edit.html.slim
h1
  | edit entry of
  = @site.name
= render 'form'

app/views/crawler/rails/sites/entries/new.html.slim
h1
  | new entry of
  = @site.name
= render 'form'

app/views/crawler/rails/sites/entries/test_run.js.erb
$('[data=result-for-test-run]').html("<%= j @out %>");